### ISSUE TITLE
About the VAE autoencoder

### ISSUE THREAD

**Issue by sh-lee-prml** [Text-to-Audio/Make-An-Audio#1]
Thanks for nice work. 

I have some questions about the VAE model. Now, I'm training the VAE model for speech latent diffusion models, and I'm so curious about what the well-trained VAE model for LDM is. 

In this work, a very low scale of weight for KL divergence is used. I hope to know the loss curve of KL divergence loss during training. Is it converged? or if not, does it not need to converge for the latent of LDM? 

Could you share your experience about the results of LDM according to different VAE models which are trained with different weight of KL divergence? 

Thanks!

**Comment by Darius-H** [comment]
The KL loss of VAE will not curve to a low level, in fact it's more like an AutoEncoder that focuses more on reconstruction performance rather than generating ability when using the VAE model alone。 And in the second stage, the powerful diffusion model will calculate the corresponding small neighborhood of the latent based on conditional information. 
![x](https://github.com/Text-to-Audio/Make-An-Audio/assets/49788663/771f150b-bba6-4345-a022-c4921a84760d)
As shown in figure, KL loss remains a high level.

**Comment by sh-lee-prml** [comment]
Thanks for the details!! 

It helps a lot for understanding.

Thanks!!

**Comment by MoayedHajiAli** [comment]
@Darius-H 
Hello Darius. Thank you very much for your great work and being amazingly responsive with the issues. 
I am wondering if you can share similar figures for the 1D VAE training using in Make-an-audio 2. Thanks!

**Comment by Darius-H** [comment]
> @Darius-H Hello Darius. Thank you very much for your great work and being amazingly responsive with the issues. I am wondering if you can share similar figures for the 1D VAE training using in Make-an-audio 2. Thanks!

duplicate of #5
